

package codebeamer.rampup.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.springframework.lang.Nullable;

/**
 * Country field
 */
@JsonPropertyOrder({
  CountryField.JSON_PROPERTY_AVAILABLE_OPTIONS
})
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class CountryField extends AbstractField {
  public static final String JSON_PROPERTY_AVAILABLE_OPTIONS = "availableOptions";
  private List<String> availableOptions;

  public CountryField() {

  }

  public CountryField availableOptions(List<String> availableOptions) {
    
    this.availableOptions = availableOptions;
    return this;
  }

  public CountryField addAvailableOptionsItem(String availableOptionsItem) {
    if (this.availableOptions == null) {
      this.availableOptions = new ArrayList<>();
    }
    this.availableOptions.add(availableOptionsItem);
    return this;
  }

   /**
   * Get availableOptions
   * @return availableOptions
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_AVAILABLE_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAvailableOptions() {
    return availableOptions;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABLE_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableOptions(List<String> availableOptions) {
    this.availableOptions = availableOptions;
  }

  @Override
  public CountryField id(Integer id) {
    this.setId(id);
    return this;
  }

  @Override
  public CountryField name(String name) {
    this.setName(name);
    return this;
  }

  @Override
  public CountryField description(String description) {
    this.setDescription(description);
    return this;
  }

  @Override
  public CountryField type(String type) {
    this.setType(type);
    return this;
  }

  @Override
  public CountryField hidden(Boolean hidden) {
    this.setHidden(hidden);
    return this;
  }

  @Override
  public CountryField valueModel(String valueModel) {
    this.setValueModel(valueModel);
    return this;
  }

  @Override
  public CountryField title(String title) {
    this.setTitle(title);
    return this;
  }

  @Override
  public CountryField legacyRestName(String legacyRestName) {
    this.setLegacyRestName(legacyRestName);
    return this;
  }

  @Override
  public CountryField trackerItemField(String trackerItemField) {
    this.setTrackerItemField(trackerItemField);
    return this;
  }

  @Override
  public CountryField mandatoryInStatuses(List<ChoiceOptionReference> mandatoryInStatuses) {
    this.setMandatoryInStatuses(mandatoryInStatuses);
    return this;
  }

  @Override
  public CountryField formula(String formula) {
    this.setFormula(formula);
    return this;
  }

  @Override
  public CountryField hideIfDependencyFormula(String hideIfDependencyFormula) {
    this.setHideIfDependencyFormula(hideIfDependencyFormula);
    return this;
  }

  @Override
  public CountryField mandatoryIfDependencyFormula(String mandatoryIfDependencyFormula) {
    this.setMandatoryIfDependencyFormula(mandatoryIfDependencyFormula);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountryField countryField = (CountryField) o;
    return Objects.equals(this.availableOptions, countryField.availableOptions) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableOptions, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountryField {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    availableOptions: ").append(toIndentedString(availableOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

