

package codebeamer.rampup.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.springframework.lang.Nullable;

/**
 * Member field
 */
@JsonPropertyOrder({
  MemberField.JSON_PROPERTY_MULTIPLE_VALUES,
  MemberField.JSON_PROPERTY_MEMBER_TYPES
})
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class MemberField extends AbstractField {
  public static final String JSON_PROPERTY_MULTIPLE_VALUES = "multipleValues";
  private Boolean multipleValues;

  /**
   * Supported member type of a member field
   */
  public enum MemberTypesEnum {
    USER("USER"),
    
    ROLE("ROLE"),
    
    GROUP("GROUP");

    private String value;

    MemberTypesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MemberTypesEnum fromValue(String value) {
      for (MemberTypesEnum b : MemberTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MEMBER_TYPES = "memberTypes";
  private List<MemberTypesEnum> memberTypes;

  public MemberField() {

  }

  public MemberField multipleValues(Boolean multipleValues) {
    
    this.multipleValues = multipleValues;
    return this;
  }

   /**
   * Multiple values state of a field
   * @return multipleValues
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_MULTIPLE_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMultipleValues() {
    return multipleValues;
  }


  @JsonProperty(JSON_PROPERTY_MULTIPLE_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMultipleValues(Boolean multipleValues) {
    this.multipleValues = multipleValues;
  }


  public MemberField memberTypes(List<MemberTypesEnum> memberTypes) {
    
    this.memberTypes = memberTypes;
    return this;
  }

  public MemberField addMemberTypesItem(MemberTypesEnum memberTypesItem) {
    if (this.memberTypes == null) {
      this.memberTypes = new ArrayList<>();
    }
    this.memberTypes.add(memberTypesItem);
    return this;
  }

   /**
   * Supported member type of a member field
   * @return memberTypes
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_MEMBER_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MemberTypesEnum> getMemberTypes() {
    return memberTypes;
  }


  @JsonProperty(JSON_PROPERTY_MEMBER_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberTypes(List<MemberTypesEnum> memberTypes) {
    this.memberTypes = memberTypes;
  }

  @Override
  public MemberField id(Integer id) {
    this.setId(id);
    return this;
  }

  @Override
  public MemberField name(String name) {
    this.setName(name);
    return this;
  }

  @Override
  public MemberField description(String description) {
    this.setDescription(description);
    return this;
  }

  @Override
  public MemberField type(String type) {
    this.setType(type);
    return this;
  }

  @Override
  public MemberField hidden(Boolean hidden) {
    this.setHidden(hidden);
    return this;
  }

  @Override
  public MemberField valueModel(String valueModel) {
    this.setValueModel(valueModel);
    return this;
  }

  @Override
  public MemberField title(String title) {
    this.setTitle(title);
    return this;
  }

  @Override
  public MemberField legacyRestName(String legacyRestName) {
    this.setLegacyRestName(legacyRestName);
    return this;
  }

  @Override
  public MemberField trackerItemField(String trackerItemField) {
    this.setTrackerItemField(trackerItemField);
    return this;
  }

  @Override
  public MemberField mandatoryInStatuses(List<ChoiceOptionReference> mandatoryInStatuses) {
    this.setMandatoryInStatuses(mandatoryInStatuses);
    return this;
  }

  @Override
  public MemberField formula(String formula) {
    this.setFormula(formula);
    return this;
  }

  @Override
  public MemberField hideIfDependencyFormula(String hideIfDependencyFormula) {
    this.setHideIfDependencyFormula(hideIfDependencyFormula);
    return this;
  }

  @Override
  public MemberField mandatoryIfDependencyFormula(String mandatoryIfDependencyFormula) {
    this.setMandatoryIfDependencyFormula(mandatoryIfDependencyFormula);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemberField memberField = (MemberField) o;
    return Objects.equals(this.multipleValues, memberField.multipleValues) &&
        Objects.equals(this.memberTypes, memberField.memberTypes) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(multipleValues, memberTypes, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberField {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    multipleValues: ").append(toIndentedString(multipleValues)).append("\n");
    sb.append("    memberTypes: ").append(toIndentedString(memberTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

