

package codebeamer.rampup.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.springframework.lang.Nullable;

/**
 * ReportGroup having subgroups.
 */
@JsonPropertyOrder({
  ReportGroupWithGroups.JSON_PROPERTY_GROUPS
})
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class ReportGroupWithGroups extends ReportGroup {
  public static final String JSON_PROPERTY_GROUPS = "groups";
  private List<ReportGroup> groups;

  public ReportGroupWithGroups() {

  }

  public ReportGroupWithGroups groups(List<ReportGroup> groups) {
    
    this.groups = groups;
    return this;
  }

  public ReportGroupWithGroups addGroupsItem(ReportGroup groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Subgroups in the group.
   * @return groups
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ReportGroup> getGroups() {
    return groups;
  }


  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroups(List<ReportGroup> groups) {
    this.groups = groups;
  }

  @Override
  public ReportGroupWithGroups type(String type) {
    this.setType(type);
    return this;
  }

  @Override
  public ReportGroupWithGroups header(String header) {
    this.setHeader(header);
    return this;
  }

  @Override
  public ReportGroupWithGroups groupingValue(String groupingValue) {
    this.setGroupingValue(groupingValue);
    return this;
  }

  @Override
  public ReportGroupWithGroups groupingValueId(Integer groupingValueId) {
    this.setGroupingValueId(groupingValueId);
    return this;
  }

  @Override
  public ReportGroupWithGroups count(Double count) {
    this.setCount(count);
    return this;
  }

  @Override
  public ReportGroupWithGroups aggregates(List<ReportAggregate> aggregates) {
    this.setAggregates(aggregates);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportGroupWithGroups reportGroupWithGroups = (ReportGroupWithGroups) o;
    return Objects.equals(this.groups, reportGroupWithGroups.groups) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groups, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportGroupWithGroups {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

