

package codebeamer.rampup.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.springframework.lang.Nullable;

/**
 * ReportGroup having rows with references.
 */
@JsonPropertyOrder({
  ReportGroupWithReferencedRows.JSON_PROPERTY_GROUPING_LEVEL,
  ReportGroupWithReferencedRows.JSON_PROPERTY_STAR_ROW,
  ReportGroupWithReferencedRows.JSON_PROPERTY_ROWS
})
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class ReportGroupWithReferencedRows extends ReportGroup {
  public static final String JSON_PROPERTY_GROUPING_LEVEL = "groupingLevel";
  private Integer groupingLevel;

  public static final String JSON_PROPERTY_STAR_ROW = "starRow";
  private Integer starRow;

  public static final String JSON_PROPERTY_ROWS = "rows";
  private List<ReportReferencedRow> rows;

  public ReportGroupWithReferencedRows() {

  }

  public ReportGroupWithReferencedRows groupingLevel(Integer groupingLevel) {
    
    this.groupingLevel = groupingLevel;
    return this;
  }

   /**
   * Get groupingLevel
   * @return groupingLevel
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_GROUPING_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getGroupingLevel() {
    return groupingLevel;
  }


  @JsonProperty(JSON_PROPERTY_GROUPING_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupingLevel(Integer groupingLevel) {
    this.groupingLevel = groupingLevel;
  }


  public ReportGroupWithReferencedRows starRow(Integer starRow) {
    
    this.starRow = starRow;
    return this;
  }

   /**
   * Get starRow
   * @return starRow
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_STAR_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStarRow() {
    return starRow;
  }


  @JsonProperty(JSON_PROPERTY_STAR_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStarRow(Integer starRow) {
    this.starRow = starRow;
  }


  public ReportGroupWithReferencedRows rows(List<ReportReferencedRow> rows) {
    
    this.rows = rows;
    return this;
  }

  public ReportGroupWithReferencedRows addRowsItem(ReportReferencedRow rowsItem) {
    if (this.rows == null) {
      this.rows = new ArrayList<>();
    }
    this.rows.add(rowsItem);
    return this;
  }

   /**
   * Get rows
   * @return rows
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_ROWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ReportReferencedRow> getRows() {
    return rows;
  }


  @JsonProperty(JSON_PROPERTY_ROWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRows(List<ReportReferencedRow> rows) {
    this.rows = rows;
  }

  @Override
  public ReportGroupWithReferencedRows type(String type) {
    this.setType(type);
    return this;
  }

  @Override
  public ReportGroupWithReferencedRows header(String header) {
    this.setHeader(header);
    return this;
  }

  @Override
  public ReportGroupWithReferencedRows groupingValue(String groupingValue) {
    this.setGroupingValue(groupingValue);
    return this;
  }

  @Override
  public ReportGroupWithReferencedRows groupingValueId(Integer groupingValueId) {
    this.setGroupingValueId(groupingValueId);
    return this;
  }

  @Override
  public ReportGroupWithReferencedRows count(Double count) {
    this.setCount(count);
    return this;
  }

  @Override
  public ReportGroupWithReferencedRows aggregates(List<ReportAggregate> aggregates) {
    this.setAggregates(aggregates);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportGroupWithReferencedRows reportGroupWithReferencedRows = (ReportGroupWithReferencedRows) o;
    return Objects.equals(this.groupingLevel, reportGroupWithReferencedRows.groupingLevel) &&
        Objects.equals(this.starRow, reportGroupWithReferencedRows.starRow) &&
        Objects.equals(this.rows, reportGroupWithReferencedRows.rows) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupingLevel, starRow, rows, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportGroupWithReferencedRows {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    groupingLevel: ").append(toIndentedString(groupingLevel)).append("\n");
    sb.append("    starRow: ").append(toIndentedString(starRow)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

