

package codebeamer.rampup.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.springframework.lang.Nullable;

/**
 * Change item for a tracker item field row.
 */
@JsonPropertyOrder({
  TrackerItemRowChange.JSON_PROPERTY_ROW_NUMBER
})
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class TrackerItemRowChange extends TrackerItemChange {
  public static final String JSON_PROPERTY_ROW_NUMBER = "rowNumber";
  private Integer rowNumber;

  public TrackerItemRowChange() {

  }

  public TrackerItemRowChange rowNumber(Integer rowNumber) {
    
    this.rowNumber = rowNumber;
    return this;
  }

   /**
   * Index of the changed row
   * @return rowNumber
  **/
  @Nullable
  @JsonProperty(JSON_PROPERTY_ROW_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRowNumber() {
    return rowNumber;
  }


  @JsonProperty(JSON_PROPERTY_ROW_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRowNumber(Integer rowNumber) {
    this.rowNumber = rowNumber;
  }

  @Override
  public TrackerItemRowChange field(FieldReference field) {
    this.setField(field);
    return this;
  }

  @Override
  public TrackerItemRowChange name(String name) {
    this.setName(name);
    return this;
  }

  @Override
  public TrackerItemRowChange oldValue(AbstractFieldValue oldValue) {
    this.setOldValue(oldValue);
    return this;
  }

  @Override
  public TrackerItemRowChange newValue(AbstractFieldValue newValue) {
    this.setNewValue(newValue);
    return this;
  }

  @Override
  public TrackerItemRowChange type(String type) {
    this.setType(type);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackerItemRowChange trackerItemRowChange = (TrackerItemRowChange) o;
    return Objects.equals(this.rowNumber, trackerItemRowChange.rowNumber) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rowNumber, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackerItemRowChange {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    rowNumber: ").append(toIndentedString(rowNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

